Add database
drumer32/filmorate pull request #11
Opened 2022-06-22 03:33 UTC by drumer32

2022-06-22 03:44 UTC, drumer32 commented
Здравствуйте, Евгений! Вышло недопонимание с Практикумом, поэтому немного долго вышло все

2022-06-22 04:55 UTC, eugene-lenkevich requested changes
Привет, Георгий, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-06-22 04:55 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film == null) {
Это скорее относится к бизнес-логике приложения, мне кажется что лучше перенести в сервис. Считается что  бизнес логика в контроллере - не гут :)

2022-06-22 04:55 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private User validation(User user) {
Пусть все таки имя метода будет глаголом - validate :)

2022-06-22 04:55 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DatabaseFilmStorage.java
> +            filmGenres.forEach(x -> jdbcTemplate.update(genreSaveSql, film.getId(), x.getId()));
Это кстати можно сделать одним запроcом, получится так сделать? :)
INSERT INTO film_genres (film_id, genre_id) VALUES (...),(...),...,(...);

2022-06-23 00:27 UTC, drumer32 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DatabaseFilmStorage.java
> +            filmGenres.forEach(x -> jdbcTemplate.update(genreSaveSql, film.getId(), x.getId()));
Сидел, думал думал. Ничего в голову не идет, как это реализовать. У нас же всегда разное количество жанров поступает. Поэтому приходится перебирать циклом

2022-06-23 03:18 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DatabaseFilmStorage.java
> +            filmGenres.forEach(x -> jdbcTemplate.update(genreSaveSql, film.getId(), x.getId()));
Ну ок, это не критично, в реальной жизни будет другой фреймворк где это будет делаться по другому :)

https://stackoverflow.com/questions/20815028/how-do-i-insert-multiple-values-into-a-postgres-table-at-once

2022-06-23 03:19 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-06-23 05:35 UTC, merged