Add friends likes
drumer32/filmorate pull request #4
Opened 2022-05-13 01:30 UTC by drumer32

2022-05-13 03:34 UTC, eugene-lenkevich requested changes
Привет, Георгий, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-05-13 03:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
А зачем storage в контроллере?
Пусть будет зависимость только на сервис, а в сервисе уже и storage и пр

наша цель наоборот делать модули, классы и пр. слабосвязанными, это делает код проще в понимании. Тут же получается что мы логику хранения размазываем между сервисом и контроллером, который вообще ничего не должен такого знать, его дело обрабатывать http-запросы :)

2022-05-13 03:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Аналогично, пусть будет в сервисе

2022-05-13 03:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmAlreadyExistException.java
> +public class FilmAlreadyExistException extends RuntimeException {
А необходимо ли тут непроверяемое исключение?
То что фильм уже существует - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
extends Exception

2022-05-13 03:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/FilmNotFoundException.java
> +public class FilmNotFoundException extends RuntimeException {
Тоже пусть исключение будет проверяемым, тут и ниже :)

2022-05-13 03:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private void validation(Film film) throws ValidationException {
Метод - это глагол, лучше назвать validate :)

2022-05-13 03:34 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getName() == null || film.getName().isBlank()) {
Тут можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2022-05-14 00:11 UTC, drumer32 commented
Здравствуйте, Евгений! Подзадержался с правками, извините) Постарался все исправить, работоспособность программы не потеряна)))

2022-05-14 03:00 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-14 04:26 UTC, merged