database added
drumer32/filmorate pull request #5
Opened 2022-05-24 04:13 UTC by drumer32

2022-05-24 04:46 UTC, drumer32 commented
Здравствуйте! Оставил картинку в репозитории db, а также ссылку в readme

2022-05-24 05:53 UTC, eugene-lenkevich requested changes
Привет, Георгий , спасибо за PR

В целом все гут :)
Одно замечание - в табличке friends поле статус имеет тип boolean, не совсем понятно, теоретически статусов может быть много, а у булева поля только два значения (три - null) может ту имеется в виду что-то другое, флаг активности, например, может поле переименовать или тип поменять чтобы было более наглядно?

2022-05-24 05:53 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public enum Genre {
Жанры ж в табличке БД хранятся :)

2022-05-25 00:53 UTC, drumer32 commented
Здравствуйте! Тут небольшая битва с Postman получилась, я думал тесты прошли, а это гит просто лаганул. Теперь все точно работает ))

2022-05-25 03:08 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-25 03:39 UTC, merged